### PR TITLE
Update robot.txt

### PR DESCRIPTION
**Pull request by WyldPhyr**
Minor edits of comments

### CODE REVIEW

**Comment by jralls** [comment]
Why do you care?

**Comment by WyldPhyr** [comment]
I'm trying to get involved in the open source community, and this seemed like a really cool project, but I don't have the technological ability to contribute anything of value to the actual pith of the project.

**Comment by jralls** [comment]
Fixing typos in comments on the website isn't really contributing. Fixing typos in what actually gets displayed might be.
Do you use GnuCash at all? Can you write well? Do you understand XML enough to learn DocBook? If so, maybe you could help out with documentation.

**Comment by gjanssens** [comment]
While it's true this doesn't really bring any functional change or improvement, I do appreciate the effort you spent on cloning the project, and preparing a PR. So I decided to merge the PR anyway.

As @jralls suggested there are many ways you can help out even if you have no strong technological background. Writing documentation is one of them. Here are a few other suggestions:
- triaging bugs, or go through the open bug reports and check if the reported problem is (still) reproducible, asking the original reporter for more details if they are missing
- helping out with translations, both for the gnucash user interface as with the documentation
- helping others with questions on the mail
- ...
A more comprehensive list of suggestions can be found [in the wiki](http://wiki.gnucash.org/wiki/Contributing_to_GnuCash)

**Comment by WyldPhyr** [comment]
Thank you @gjanssens

**Pull request merged**
