### PR TITLE
Update pt.po

### PR DESCRIPTION
**Pull request by pmraps**

### CODE REVIEW

**Comment by fellen** [comment]
Thanks, but there were 4 (changed) messages not merged. Do you want to  add them, too?

**Comment by fellen** [comment]
There is currently a problem to update the main site. To see the result of your work use https://www.gnucash.org/beta/index.phtml?lang=pt_PT

**Comment by pmraps** [comment]
Hi,
thank you for your trouble. I probably should have mentioned this on the commit messages,
I found something called GitHub Desktop, so I decided to try it, hoping it would take care of the possible problems.
This pull request was my mistake, as usual, as the translation was not yet fully reviewed.
I'll try again latter.
I read the entire site and found no problem. Could you specify what is wrong, please?

**Comment by fellen** [comment]
> I found something called GitHub Desktop

That should reduce the trouble with git and github. If you think, it is usefull, you can add asection to https://wiki.gnucash.org/wiki/Translation, perhaps in #Pull_Requests_at_GitHub. 

> Could you specify what is wrong, please?

msgattrib  --untranslated po/pt.po
```
#: download.phtml:6
msgid ""
"Download executable bundles of the <span class=\"gnucash\">GnuCash</span> "
"program inclusive documentation or the source files here. Several versions "
"are available for recent and older operating systems."
msgstr ""

#: news.phtml:5
msgid "Announcement of New Releases, Server Maintenance,…"
msgstr ""

#: sizing.phtml:5
msgid "This is an ancient page about Gnucash's code size."
msgstr ""
```
Each page got a short description at the beginning and in the metadata..

msgattrib --only-fuzzy po/pt.po

```
#: viewdoc.phtml:162
#, fuzzy, php-format
#| msgid ""
#| "It seems your browser doesn't support iframes. To view the requested page "
#| "in a separate window, please <a href=\"%s\" target=\"_new\">click here</"
#| "a>."
msgid ""
"It seems your browser doesn't support iframes. To view the requested page in "
"a separate window, please <a href=\"%s\" target=\"_blank\">click here</a>."
msgstr ""
"Parece que o seu navegador não suporta iframes. Para ver a página pedida "
"numa janela separada, por favor, <a href=\"%s\" target=\"_new\">clique aqui</"
"a>."
```
`target="_blank"` is invalid in HTML5. Some browsers might behave strange. At some point I want to replace such technical details by another %s.

**Comment by fellen** [comment]
Continued in PR 29.

**Pull request merged**
