### PR TITLE
Update pt.po

### PR DESCRIPTION
**Pull request by pmraps**
Obsolete messages removed. Thank you.

### CODE REVIEW

**Comment by fellen** [comment]
Did you see the message  `This branch cannot be rebased due to conflicts` at https://github.com/Gnucash/gnucash-htdocs/pull/30?
This PR in the current form would revert the commit, where you changed `transação`to `transacção` …
Perhaps you should sometimes have a look at https://git-scm.com/book/pt-pt/v2/Ramificação-do-Git-Branches-in-a-Nutshell?

Because resolving the conflicts would be more time consuming, I pushed the intended change as commit 5352108.

Thanks!

**Comment by fellen** [comment]
Pedro, I just saw https://github.com/Gnucash/gnucash-htdocs/blob/535210881a7faca96bc5373feadfa189ea2b8bff/po/pt.po#L762-L766

Do you think, we should link https://wiki.gnucash.org/wiki/Pt/GnuCash instead of de?

A comment about the opportunity will be in future po files.

**Comment by pmraps** [comment]
First of all, thank you very much for all your trouble and patience.

About the Wiki, that page is clearly Brazilian, which is currently a completely different language with its own rules, grammar and spelling. They even use different words, like 'File' -> Portuguese=Ficheiro, Brazilian=Arquivo, etc.

It should NOT be linked to the Portuguese (Portugal) translations.
If it wasn't such a huge task, I would offer myself to create a Portuguese version. But, if there has to be a link, please link to the English wiki.

Again. many thanks.

**Comment by fellen** [comment]
The English link is already there. I have to confess, for me both are latin "dialects" and do not know much about the differences. In some cases I prefer Dutch over English because it is closer to German. Analog some of your readers might prefer pt_BR over en_US, if pt_PT is not available, but that is up to you.

**Comment by pmraps** [comment]
Well then, English is the 'official' worldwide international language and here is taught at every school, so there shouldn't be any problems. Please leave as is.
Thank you. Again and again.

**Pull request closed without merging**
