### PR TITLE
Linux: Add Solus installation instructions

### PR DESCRIPTION
**Pull request by kyrios123**
[Solus](https://solus-project.com) is in the top 10 of the most popular linux distributions according to [distrowatch](https://www.distrowatch.com/dwres.php?resource=popularity)

GnuCash repository for this distro is available [here](https://dev.solus-project.com/source/gnucash/)

Signed-off-by: Pierre-Yves <pyu@riseup.net>

### CODE REVIEW

**Comment by gjanssens** [comment]
Thanks!

**Comment by jralls** [comment]
No. GnuCash is not a vehicle for you to advertise your distro.

**Comment by jralls** [comment]
@gjanssens: @kyrios123 is one of the primary contributors to Solus. The [Solus Wikipedia article](https://en.wikipedia.org/wiki/Solus_(operating_system)) reads like a press release; it was clearly written by the Solus team as an advertisement. Distrowatch is easily manipulated by botnets and is of no value in assessing anything. A search of gnucash-user for "solus" returns exactly nothing.

There's no reason for us to promote these guys.

**Comment by kyrios123** [comment]
@jralls I am indeed a contributor of Solus though I am not a member of the core team.
The reason I mentioned distrowatch is because some people don't know what Solus is and it is the only site I know that provides a ranking even if not reliable.

GnuCash was long awaited by many Solus users but because of webkit1 prerequisite, it was only added when version 3 was released.

Personally I just submitted a patch for [version 3.2 update](https://dev.solus-project.com/D3158). And while reading the information, I saw the download page so I went to #gnucash IRC channel to ask if instructions for Solus could be added and I was told to submit a PR here which I did.

I don't understand your reaction. I did **just the same** as was is currently available for other distros meaning telling the users how to find and install the application. I did respect the alphabetical order, did not put any link, advertisement message or whatever.

**Comment by jralls** [comment]
@kyrios123 because (aside from the defunct Mandriva) the other distros on that page are major players, so this makes it look like GnuCash is somehow endorsing Solus, which isn't. Folks associated with Solus appear to put a lot of effort into self-promotion and I object to GnuCash's website being part of that effort.

**Pull request merged**
